version: '3.3'

services:
  cotizador-agro:
    container_name: cotizador-agro
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3048:3048"
    restart: unless-stopped
    # Add healthcheck to ensure the application is running
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3048"]
      interval: 10s
      timeout: 5s
      retries: 3
