version: '3.3'

services:
  cuotas-socios:
    container_name: cuotas-socios
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3046:3046"
    restart: unless-stopped
    # Add healthcheck to ensure the application is running
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3046"]
      interval: 10s
      timeout: 5s
      retries: 3
